name: Update VERSION on Release

on:
  release:
    types: [published]

jobs:
  update-version-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write VERSION with release tag
        run: |
          echo "${{ github.event.release.tag_name }}" > VERSION

      - name: Commit and push VERSION
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "chore: update VERSION to ${{ github.event.release.tag_name }}" || echo "no changes"
          git push
